### ISSUE TITLE
ScrollView Issue

### ISSUE THREAD

**Issue by DripMicro** [Backendeng/Unity_Authentification_Chatbox#73]
Hi, how are u?

I saw Sheild and Cosmetics and Resources ScrollView are not working well.

Need to fix it.

**Comment by Backendeng** [comment]
Yes, I will fix it soon.

**Comment by DripMicro** [comment]
And Title GrayScale is not working.

**Comment by Backendeng** [comment]
Yes. I checked, I will fix it too.

**Comment by DripMicro** [comment]
Create Discussion

**Comment by Backendeng** [comment]
got it
